; Nib assembly — generated by nib bind

; === lcd_clear ===
lcd_clear:
    mov AX, 47104
    mov ES, AX
    mov AX, 0
    mov DI, AX
    mov AX, 480
    mov CX, AX
    ; asm preserves(DI, CX, FLAGS) 

        rep stosb
    
    ret

; === lcd_putchar ===
lcd_putchar:
    mov AX, 47104
    mov ES, AX
    ; asm preserves(DI, FLAGS) 

        stosb
    
    ret

; === main ===
main:
    mov AL, 32
    call lcd_clear
    mov DI, 0
    mov AL, 65
    call lcd_putchar
    mov DI, 1
    mov AL, 66
    call lcd_putchar
    ret
