; Nib assembly — generated by nib bind

; === fill ===
fill:
    mov AX, 47104
    mov ES, AX
    ; asm preserves(DI, CX, FLAGS) 

        rep stosb
    
    ret

; === scroll_line ===
scroll_line:
    mov AX, 0
    mov ES, AX
    ; asm preserves(SI, DI, CX, FLAGS) 

        rep movsb
    
    ret

; === main ===
main:
    mov DI, 0
    mov AL, 32
    mov CX, 80
    ; call fill
    call fill
    mov SI, 80
    mov DI, 0
    mov CX, 80
    ; call scroll_line
    call scroll_line
    ret
